name: Frontend components CI pipeline
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: './.github/actions/setup-environment'
      - uses: './.github/actions/cypress-cache'
      - name: Install dependencies
        run: npm i
  build:
    runs-on: ubuntu-24.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: './.github/actions/setup-environment'
      - uses: nrwl/nx-set-shas@v4
      - name: Build
        run: npm run build
  unit-test:
    runs-on: ubuntu-24.04
    needs: [install]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: './.github/actions/setup-environment'
      - uses: nrwl/nx-set-shas@v4
      - name: Run unit tests
        run: npm run test:unit
  component-test:
    runs-on: ubuntu-24.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: './.github/actions/setup-environment'
      - uses: nrwl/nx-set-shas@v4
      - uses: './.github/actions/cypress-cache'
      - name: Install deps
        shell: bash
        run: npm i
      - name: Run component tests
        uses: cypress-io/github-action@v6
        with:
          command: npx nx affected -t test:component --exclude=demo --outputStyle=static --parallel=1
  lint:
    runs-on: ubuntu-24.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: './.github/actions/setup-environment'
      - uses: nrwl/nx-set-shas@v4
      - name: Lint
        run: npx nx affected -t test:lint --exclude=demo --outputStyle=static
  commitlint:
    needs: [install]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: './.github/actions/setup-environment'
      - name: install
        shell: bash
        run: npm i
      - name: Validate current commit on push
        shell: bash
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose
      - name: Validate PR commits
        shell: bash
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
  check-circular-imports:
    runs-on: ubuntu-24.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: './.github/actions/setup-environment'
      - uses: nrwl/nx-set-shas@v4
      - name: install
        shell: bash
        run: npm i
      - name: Check circular imports
        run: npx nx affected -t test:circular-dependencies --exclude=demo --outputStyle=static
  release:
    runs-on: ubuntu-24.04
    needs: [install, build, unit-test, component-test, lint, commitlint, check-circular-imports]
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_BOT_TOKEN }}
      - uses: './.github/actions/release'
        with:
          gh_token: ${{ secrets.GH_BOT_TOKEN }}
          npm_token: ${{ secrets.NPM_TOKEN }}
          gh_name: ${{ secrets.BOT_NAME }}
          gh_email: ${{ secrets.BOT_EMAIL }}
